---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./pvc.yaml
  - ./referencegrant.yaml
  - ../../templates/base
  # Flux-Kustomizations
  - ./autobrr/ks.yaml
  # - ./cross-seed/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./media-browser/ks.yaml
  - ./prowlarr/ks.yaml
  # - ./qbittorrent/ks.yaml
  - ./sabnzbd/ks.yaml
patchesJson6902:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: default
    target:
      group: notification.toolkit.fluxcd.io
      kind: Alert
      name: alert-manager
      version: v1beta3
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: default
    target:
      group: notification.toolkit.fluxcd.io
      kind: Provider
      name: alert-manager
      version: v1beta3
