---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  storageClassName: csi-s3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
