---
creation_rules:
  - path_regex: kubernetes/.*\.secret(\.sops)?\.yaml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1myxsdyjgwefpljpsvf0n6pvjr4n9ygz0nh3zy7wkfjnqdg54jayqwaqqfm
  - path_regex: kubernetes/.*\.secret(\.sops)?\.env
    key_groups:
      - age:
          - age1myxsdyjgwefpljpsvf0n6pvjr4n9ygz0nh3zy7wkfjnqdg54jayqwaqqfm
