---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/terraform"

env:
  KUBECONFIG: "{{.TERRAFORM_DIR}}/target/generated/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"

includes:
  flux: .taskfiles/Flux/Taskfile.yaml
  terraform: .taskfiles/Terraform/Taskfile.yaml

tasks:
  default:
    silent: true
    cmd: task -l
