---
groups:
  - name: autobrr
    rules:
      - alert: AutobrrNetworkUnhealthy
        expr: |
          sum by (app) (count_over_time({app="autobrr"} |~ "(?i)network unhealthy"[2m])) > 0
        for: 2m
        labels:
          severity: critical
          category: logs
        annotations:
          app: "{{ $labels.app }}"
          summary: "{{ $labels.app }} has a unhealthy network"

  # - name: plex
  #   rules:
  #     - alert: PlexDatabaseBusy
  #       expr: |
  #         sum by (app) (count_over_time({app="plex"} |~ "(?i)retry busy DB"[2m])) > 0
  #       for: 2m
  #       labels:
  #         severity: critical
  #         category: logs
  #       annotations:
  #         app: "{{ $labels.app }}"
  #         summary: "{{ $labels.app }} is experiencing database issues"

  # - name: cross-seed
  #   rules:
  #     - alert: CrossSeedDatabaseMalformed
  #       expr: |
  #         sum by (app) (count_over_time({app="cross-seed"} |~ "(?i)database disk image is malformed"[1h])) > 0
  #       for: 2m
  #       labels:
  #         severity: critical
  #         category: logs
  #       annotations:
  #         app: "{{ $labels.container }}"
  #         summary: "{{ $labels.container }} is experiencing database issues"
