---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insights-agent
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: insights-agent-secret
    template:
      engineVersion: v2
      data:
        token: "{{ .INSIGHTS_AGENT_TOKEN }}"
  dataFrom:
    - extract:
        key: insights-agent
