---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: tandoor
  namespace: tandoor
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: tandoor
  to:
    - group: ""
      kind: Service
