---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: seurity
  namespace: seurity
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: seurity
  to:
    - group: ""
      kind: Service
