---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: csi-s3-secret
    template:
      engineVersion: v2
      data:
        accessKeyID: "{{ .ACCESS_KEY_ID }}"
        secretAccessKey: "{{ .SECRET_ACCESS_KEY }}"
        endpoint: "{{ .ENDPOINT }}"
  dataFrom:
    - extract:
        key: csi-s3
