---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./referencegrant.yaml
  - ../../templates/base
  # Flux-Kustomizations
  - ./grafana/ks.yaml
  # - ./insights-agent/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./thanos/ks.yaml
patchesJson6902:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: observability
    target:
      group: notification.toolkit.fluxcd.io
      kind: Alert
      name: alert-manager
      version: v1beta3
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: observability
    target:
      group: notification.toolkit.fluxcd.io
      kind: Provider
      name: alert-manager
      version: v1beta3
