---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: actions-runner-system
  namespace: actions-runner-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: actions-runner-system
  to:
    - group: ""
      kind: Service
