---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tandoor-secret
    template:
      engineVersion: v2
      data:
        DB_ENGINE: django.db.backends.postgresql
        POSTGRES_DB: &dbName tandoor
        POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_USER: &dbUser "{{ .TANDOOR_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .TANDOOR_POSTGRES_PASS }}"
        POSTGRES_PORT: "5432"
        SECRET_KEY: "{{ .TANDOOR_SECRET_KEY }}"
        REMOTE_USER_AUTH: "1"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: tandoor
    - extract:
        key: cloudnative-pg
