---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tandoor
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-01-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: tandoor-secret
          init-02-chmod:
            image: &image
              repository: vabene1111/recipes
              tag: 1.5.13@sha256:2d323943bc33e688f8e0fe73de72cda5816044bbb451924703204b7ceb2a268b
            envFrom: *envFrom
            command:
              - sh
              - -c
              - |
                set -e
                source venv/bin/activate
                echo "Updating database"
                python manage.py migrate
                python manage.py collectstatic_js_reverse
                python manage.py collectstatic --noinput
                echo "Setting media file attributes"
                chown -R 568:568 /opt/recipes/mediafiles
                find /opt/recipes/mediafiles -type d | xargs -r chmod 755
                find /opt/recipes/mediafiles -type f | xargs -r chmod 644
                echo "Setting static file attributes"
                chown -R 568:568 /opt/recipes/staticfiles
                find /opt/recipes/staticfiles -type d | xargs -r chmod 755
                find /opt/recipes/staticfiles -type f | xargs -r chmod 644
                echo "Done"
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
        containers:
          main:
            image: *image
            env:
              TZ: Europe/Warsaw
              DEBUG: "0"
              ALLOWED_HOSTS: "*"
              GUNICORN_MEDIA: "0"
            envFrom: *envFrom
            command:
              - /opt/recipes/venv/bin/gunicorn
              - -b
              - :8080
              - --access-logfile
              - "-"
              - --error-logfile
              - "-"
              - --log-level
              - INFO
              - recipes.wsgi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
    service:
      main:
        ports:
          http:
            port: *port
    route:
      main:
        # annotations:
        #   konghq.com/plugins: authelia-forward
        enabled: true
        parentRefs:
          - name: kong
            namespace: network
        hostnames:
          - recipes.janpuc.com
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - port: http
                name: main
    persistence:
      media:
        enabled: true
        existingClaim: tandoor-media
        globalMounts:
          - path: /opt/recipes/mediafiles
      static:
        enabled: true
        existingClaim: tandoor-static
        globalMounts:
          - path: /opt/recipes/staticfiles
      tmp:
        type: emptyDir
