---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      proxy:
        annotations:
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/internal: "false"
          external-dns.alpha.kubernetes.io/hostname: oke.janpuc.com
      resources:
        requests:
          cpu: 10m
        limits:
          memory: 128Mi
    gateway:
      proxy:
        annotations:
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/internal: "false"
          external-dns.alpha.kubernetes.io/hostname: oke.janpuc.com
      extraConfigMaps:
        - name: authelia-forward-configmap
          mountPath: /etc/kong/custom
      env:
        UNTRUSTED_LUA: "on"
      resources:
        requests:
          cpu: 10m
        limits:
          memory: 512Mi
