---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gateway.yaml
  - ./gatewayclass.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: authelia-forward-configmap
    files:
      - authelia-forward.lua=./resources/authelia-forward.lua
generatorOptions:
  disableNameSuffixHash: true
