---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ../../templates/bases
  # Flux-Kustomizations
  - ./csi-s3/ks.yaml
  - ./local-path-provisioner/ks.yaml
patchesJson6902:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: storage
    target:
      group: notification.toolkit.fluxcd.io
      kind: Alert
      name: alert-manager
      version: v1beta3
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: storage
    target:
      group: notification.toolkit.fluxcd.io
      kind: Provider
      name: alert-manager
      version: v1beta3
